import i18n from "i18next"
import { initReactI18next } from "react-i18next"
import LanguageDetector from "i18next-browser-languagedetector"

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: true,
    resources: {
      en: {
        translation: {
          "login-h1": "Find your match",
          "sign-up": "Sign up",
          "sign-in": "Sign in",
          "sign-up-popup-title": "Sign up",
          "sign-in-popup-title": "Sign in",
          "close-popup": "Close",
          "name": "Name",
          "email": "Email",
          "email-placeholder": "Enter your email",
          "password": "Password",
          "password-placeholder": "Enter your password",
          "password-check": "Confirm password",
          "password-check-placeholder": "Enter your password again",
          "gender": "Gender",
          "gender-interest": "You're interested in",
          "first-name": "First name",
          "first-name-placeholder": "Enter your first name",
          "second-name": "Second name",
          "second-name-placeholder": "Введіть вашу фамілію",
          "man": "Man",
          "men": "Men",
          "woman": "Woman",
          "women": "Women",
          "both": "Both",
          "day": "Day",
          "day-placeholder": "Day of birth",
          "month": "Month",
          "month-placeholder": "Month of birth",
          "year": "Year",
          "year-placeholder": "Year of birth",
          "bio": "Bio",
          "bio-placeholder": "Tell something about yourself",
          "picture-url": "Your picture URL",
          "picture-url-placeholder": "Enter your picture URL",
          "create-account": "Create account",
          "onboarding-page": "Onboarding",
          "dashboard-page": "Dashboard",
          "chat-page": "Chat",
          "admin-page": "Admin Page",
          "log-out": "Log out",
          "chat-not-selected": "Chat not selected",
          "enter-your-message": "Enter your message...",
          "send-message": "Send message",
          "all-users": "All users",
          "matches": "Matches",
          "close": "Close"
        },
      },
      ua: {
        translation: {
          "login-h1": "Знайди собі пару",
          "sign-up": "Зареєструватись",
          "sign-in": "Ввійти",
          "sign-up-popup-title": "Реєстрація",
          "sign-in-popup-title": "Вхід",
          "close-popup": "Закрити",
          "name": "Ім'я",
          "email": "Пошта",
          "email-placeholder": "Введіть свою електронну пошту",
          "password": "Пароль",
          "password-placeholder": "Введіть свій пароль",
          "password-check": "Повторіть пароль",
          "password-check-placeholder": "Введіть свій пароль ще раз",
          "gender": "Стать",
          "gender-interest": "Вас цікавлять",
          "first-name": "Ваше ім'я",
          "first-name-placeholder": "Введіть ваше ім'я",
          "second-name": "Ваша фамілія",
          "second-name-placeholder": "Введіть вашу фамілію",
          "man": "Чоловік",
          "men": "Чоловіки",
          "woman": "Жінка",
          "women": "Жінки",
          "both": "Всі",
          "day": "День",
          "day-placeholder": "День вашого народження",
          "month": "Місяць",
          "month-placeholder": "Місяць вашого народження",
          "year": "Рік",
          "year-placeholder": "Рік вашого народження",
          "bio": "Про себе",
          "bio-placeholder": "Напишіть щось про себе",
          "picture-url": "Посилання на ваше фото",
          "picture-url-placeholder": "Вставте посилання на ваше фото",
          "create-account": "Створити акаунт",
          "onboarding-page": "Ваш профіль",
          "dashboard-page": "Панель знайомств",
          "chat-page": "Чат",
          "admin-page": "Для адмінів",
          "log-out": "Вийти",
          "chat-not-selected": "Чат не вибраний",
          "enter-your-message": "Введіть ваше повідомлення",
          "send-message": "Відправити повідомлення",
          "all-users": "Всі користувачі",
          "matches": "Лайкнуті користувачі",
          "close": "Закрити"
        },
      },
    },
  });

export default i18n